get Glare to compile on latest version of Gleam
Endercheif/glare pull request #1
Opened 2023-11-29 01:29 UTC by ajstrand

My PR gets glare to compile on the latest version of gleam, since there was a lot of syntax changes needed.

2023-11-29 07:29 UTC, Nicd commented on example/demo/gleam.toml
> +glare = {path = "/Users/alex/Documents/projects/glare"}
Probably not what you want to merge.

2023-12-06 06:40 UTC, ajstrand commented on example/demo/gleam.toml
> +glare = {path = "/Users/alex/Documents/projects/glare"}
I was using the glare library as a local dependency. Im not sure how to abstract getting the path to the library in something like a .toml file. Maybe theres a library i can use to do that.

2023-12-06 06:45 UTC, ajstrand commented on example/demo/gleam.toml
> +glare = {path = "/Users/alex/Documents/projects/glare"}
You cant use variables inside .toml files, so ill have to set this value to a placeholder for a new commit.

2023-12-17 03:25 UTC, Enderchief requested changes
Thanks so much. Sorry for the late review.

2023-12-17 03:25 UTC, Enderchief commented on example/demo/gleam.toml
> +glare = {path = "/Users/alex/Documents/projects/glare"}
```suggestion
glare = {path = "../../"}
```

2023-12-17 03:25 UTC, merged